jobs:
- job: RunAppMain
  displayName: Run App Main
  workspace:
    clean: all

  steps:
  - template: step-install-node.yml
  
  - template: step-install-dependencies.yml
  
  - script: npm run build
    displayName: Build TypeScript
    workingDirectory: $(WORK_DIR_PATH)
  
  - script: npm run dist
    displayName: Run application
    workingDirectory: $(WORK_DIR_PATH)
    